env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
rules: {
  "prettier/prettier": "error",
  "no-unused-vars": "warn",
  "import/no-extraneous-dependencies": false
}