# This is a basic workflow to help you get started with Actions

name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run install
        run: npm ci
        
      - name: run test
        run: npm run test

